Favorite Movie Add and Edit
anthogr45/MovieFinder pull request #24
Opened 2024-01-26 19:36 UTC by anthogr45

2024-01-26 22:40 UTC, jizhang80 requested changes
as the comment in the code, please check it then submit it again. We need really workable code.

2024-01-26 22:40 UTC, jizhang80 commented on client/src/components/MovieCard.jsx
> +  const { isFavorite, addFavoriteMovie, removeFavoriteMovie } = useFavoriteMovies();
In your useFavoriteMovies, there is no "isFavorite" function.

2024-01-26 22:40 UTC, jizhang80 commented on client/src/pages/favMovie.jsx
you need a isFavorite() function here.

2024-01-26 22:40 UTC, jizhang80 commented on package.json
Please do not leave those conflict signs here.
and I don't think you should install "@material-ui/core": "^4.12.3", "@material-ui/icons": "^4.11.2", in root package.json file.

2024-01-27 01:08 UTC, closed without merging

2024-01-27 01:08 UTC, anthogr45 commented
Further testing